version: '3.8'
services:
  test-db:
    container_name: hftx-test-db
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hftx_test
    ports:
      - '25432:5432'
