version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hftx
    ports:
      - '15432:5432'
    volumes: 
      - ./db-data:/var/lib/postgresql/data
